export const customStyles = {
  control: (provided, state) => ({
    ...provided,
    backgroundColor: 'tramsparent',
    border: '1px solid rgba(255,255,255, 0.1)',
    borderRadius: '6px',
    boxSizing: 'border-box',
    cursor: 'pointer',
    height: '38px',
    fontSize: '14px',
    maxWidth: '168px',
    outline: 'none',
    paddingLeft: '6px',
    paddingTop: 0,
    pointerEvents: state.selectProps.disabled && 'none',
    transition: 'all .2s ease-in-out',
    ':hover': {
      border: (state.isFocused || state.selectProps.error) && '1px solid transparent',
    },
  }),
  dropdownIndicator: (provided, { selectProps: { menuIsOpen, disabled } }) => ({
    ...provided,
    color: 'red',
    margin: 0,
    opacity: disabled && 0.4,
    position: 'absolute',
    right: '8px',
    top: '10px',
    transform: menuIsOpen && 'rotate(180deg)',
    transition: 'transform 0.3s ease-out',
  }),
  groupHeading: () => ({
    color: 'black',
    fontWeight: 'bold',
    marginLeft: '10px',
    textTransform: 'capitalize',
  }),
  input: (styles) => ({
    ...styles,
    boxSizing: 'border-box',
    marginTop: 0,
    caretColor: 'transparent',
  }),
  menu: (provided) => ({
    ...provided,
    margin: 0,
    top: '38px',
    maxWidth: '168px',
  }),
  menuList: (provided) => ({
    ...provided,
    borderRadius: '6px',
    paddingTop: 0,
    paddingBottom: 0,
    maxHeight: '182px',
  }),
  option: (styles, { isDisabled, isSelected, selectProps: { menuIsOpen } }) => ({
    ...styles,
    alignItems: 'center',
    backgroundColor: isSelected && 'transparent',
    borderRadius: menuIsOpen && '6px',
    color: 'black',
    cursor: isDisabled ? 'not-allowed' : 'pointer',
    display: 'flex',
    height: '30px',
    marginLeft: '6px',
    ':last-of-type': {
      borderBottom: 'none',
    },
    textTransform: 'capitalize',
  }),
  placeholder: (styles, state) => ({
    ...styles,
    color: 'white',
    opacity: state.selectProps.disabled && 0.4,
    transition: 'transform 0.3s ease-out',
  }),
  singleValue: (styles) => ({
    ...styles,
    bottom: 0,
    color: 'white',
    overflow: 'visible',
    position: 'absolute',
  }),
};
