export const SPECIES_SELECTED_COOKIE = 'species_selected';

export const NAVIGATION = {
  HOME: 1,
  REGION: 2,
  SPECIES: 3,
  DATA_LAYER: 4,
  BIO_IND: 5,
  REGION_ANALYSIS: 6,
  TRENDS: 7,
  EXPLORE_SPECIES: 8,
}

export const LAYER_OPTIONS = {
  PROTECTED_AREAS: 'PROTECTED_AREAS',
  PROPOSED_PROTECTED_AREAS: 'PROPOSED_PROTECTED_AREAS',
  PROVINCES: 'PROVINCES',
  PROVINCES_VECTOR: 'PROVINCES_VECTOR',
  PROVINCES_REGION_VECTOR: 'PROVINCES_REGION_VECTOR',
  PRIORITY_AREAS: 'PRIORITY_AREAS',
  COMMUNITY_FORESTS: 'COMMUNITY_FORESTS',
  HABITAT: 'HABITAT',
}

export const PROVINCE_FEATURE_GLOBAL_SPI_LAYER_ID = 'e3dca98a5bf74c9898c30f72baf6b1ba';
export const PROVINCE_FEATURE_GLOBAL_OUTLINE_ID = 'c6bc2248f053422da9d8d30ce591ca16';

// DRC LAYERS
export const PROTECTED_AREA_FEATURE_URL = '6b13aac7863a44bb915d1847dfc5dfd9';
export const EXPERT_RANGE_MAP_URL = 'https://next-api-dot-map-of-life.appspot.com/2.x/species/drc_rangemap';
export const TREND_MAP_URL = 'https://next-api-dot-map-of-life.appspot.com/2.x/species/drc_trend'

// LIBERIA LAYERS
export const PROTECTED_AREA_LIB_FEATURE_URL = 'db67d0fa645047a18d83c1c5a67e9d99';

// GUINEA LAYERS
export const PROTECTED_AREA_GIN_FEATURE_URL = 'fd86210b977c4ec3935f297559dcd80b';

// SIERRA LEONE
export const PROTECTED_AREA_SLE_FEATURE_URL = 'af483c5930f9447080c9e49f8698882d';

// GUYANA
export const PROTECTED_AREA_GUY_FEATURE_URL = 'd610d9ad96bc4071a31b3aacdfbf844d';

export const LAYER_TITLE_TYPES = {
  EXPERT_RANGE_MAPS: 'EXPERT RANGE MAPS',
  POINT_OBSERVATIONS: 'POINT OBSERVATIONS',
  REGIONAL_CHECKLISTS: 'REGIONAL CHECKLISTS',
  TREND: 'TREND',
}

export const INITIAL_LAYERS = [
  'INITIAL_COUNTRY_LAYER',
  'INITIAL_GROUP_LAYER',
  'cities_labels_layer',
  'regions_labels_layer',
  'countries_labels_layer',
  'landscape_features_labels_layer',
  'admin_areas_feature_layer',
];

export const REGION_OPTIONS = {
  PROVINCES: 'PROVINCES',
  PROTECTED_AREAS: 'PROTECTED_AREAS'
}
